spring:
  data:
    mongodb:
      port: 27017

      host: localhost
      database: Real
      #host: 3.36.221.206
      #database: admin
      #username: eruty
      #password: eruty

  thymeleaf:
    prefix: classpath:/templates/

#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: yusung@eruty.co.kr
#    password: mwrukccdextdkxqh
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true

logging:
  level:
    org.springframework.data.mongodb: DEBUG